# Generated by Django 5.2.3 on 2025-06-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('standard', 'Standard'), ('admin', 'Admin')], default='standard', max_length=10),
        ),
    ]
