# Generated by Django 5.2.3 on 2025-11-07 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_profile_picture_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MutedInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_instructors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='users_muted_user_id_3d0f5f_idx'), models.Index(fields=['instructor'], name='users_muted_instruc_85b6cc_idx')],
                'unique_together': {('user', 'instructor')},
            },
        ),
    ]
