# Generated by Django 5.2.3 on 2025-06-27 12:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('points', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField()),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('month_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['period_type', 'year', 'week_number', 'rank'], name='feed_leader_period__600f65_idx'), models.Index(fields=['period_type', 'year', 'month_number', 'rank'], name='feed_leader_period__2cb31a_idx')],
                'unique_together': {('user', 'period_type', 'year', 'month_number'), ('user', 'period_type', 'year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('weekly_points', models.PositiveIntegerField(default=0)),
                ('monthly_points', models.PositiveIntegerField(default=0)),
                ('last_weekly_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_monthly_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_reactions', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('weekly_reactions', models.PositiveIntegerField(default=0)),
                ('weekly_comments', models.PositiveIntegerField(default=0)),
                ('monthly_reactions', models.PositiveIntegerField(default=0)),
                ('monthly_comments', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['-total_points'], name='feed_usersc_total_p_f40794_idx'), models.Index(fields=['-weekly_points'], name='feed_usersc_weekly__7fc036_idx'), models.Index(fields=['-monthly_points'], name='feed_usersc_monthly_32cff9_idx'), models.Index(fields=['user'], name='feed_usersc_user_id_af579d_idx')],
            },
        ),
    ]
