# Generated by Django 5.2.3 on 2025-07-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='poll_votes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='monthly_poll_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='total_poll_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='weekly_poll_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
