# Generated by Django 5.2.3 on 2025-11-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_leaderboardentry_poll_votes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😂'), ('sad', '😢'), ('angry', '😠')], max_length=10),
        ),
    ]
